/* eslint-disable */
// This file is autogenerated, do not edit it by hands
// Use mapping/build.js instead

module.exports = require('./convert')(
  "=\"#'()*+-/:;<>?@[\\]_z{|}",
  "¡¨·´)=(¿'-Ññ;:_\"`ç+?y^Ç*"
)
