/* eslint-disable */
// This file is autogenerated, do not edit it by hands
// Use mapping/build.js instead

module.exports = require('./convert')(
  ".exports=\"#$%&'()*+,-/0123456789:;<>@[]^_`abcdfghijklmnquvwyz{}~",
  "юучзщкеыһЭІҢҒ:эҰҚҮҺбө№қ\"әіңғ,.үұЖжБЮӘхъ;Ө(фисвапршолдьтйгмцняХЪ)"
)
